from aiogram.dispatcher.filters.state import State,StatesGroup

class Full_info_user(StatesGroup):
    fullname = State()
    date = State()
    phone = State()
    addphone = State()
    malumot = State()
    manzil = State()
    oilaviy_holat = State()
    sud_holat = State()
    qiziqish = State()
    chidam = State()
    jamoa = State()
    computer = State()
    photo = State()
    company = State()
    newcompany = State()
    last_summa = State()
    new_summa = State()
    time_job = State()
    know_lang = State()
    know_lang_degree = State()
    nima_uchun = State()
    about_us = State()
    comfirm = State()

